import type { Argon2Profile } from './types';

const PCBK_MAGIC = 'PCBK';
const PCBK_FORMAT_VERSION = 1;
const PCBK_HEADER_VERSION = 1;
const PCBK_RECORD_VERSION = 1;
const PCBK_FLAGS = 0;

const PCBK_HEADER_AUTH_INFO = 'PCBK/1/header-auth';
const PCBK_KEY_WRAP_INFO = 'PCBK/1/key-wrap';
const PCBK_HKDF_ALGORITHM = 'HKDF-SHA-256';
const PCBK_KDF_ALGORITHM = 'argon2id';
const PCBK_KEY_WRAP_ALGORITHM = 'AES-GCM-256';
const PCBK_RECORD_CIPHER_ALGORITHM = 'AES-GCM-256';

const PCBK_SALT_BYTES = 16;
const PCBK_BACKUP_ID_BYTES = 16;
const PCBK_ROOT_KEY_BYTES = 32;
const PCBK_CONTENT_KEY_BYTES = 32;
const PCBK_WRAP_IV_BYTES = 12;
const PCBK_RECORD_NONCE_PREFIX_BYTES = 4;
const PCBK_RECORD_NONCE_BYTES = 12;
const PCBK_HEADER_AUTH_TAG_BYTES = 32;
const PCBK_AES_GCM_TAG_BITS = 128;
const PCBK_CLEAR_HEADER_LENGTH_BYTES = 4;
const PCBK_RECORD_HEADER_LENGTH_BYTES = 4;
const PCBK_BIP39_WORD_COUNT = 12;
const PCBK_BIP39_ENTROPY_BITS = 128;

const ARGON2_RECOMMENDED_STANDARD_PROFILE: Argon2Profile = {
	name: 'recommended-standard',
	memoryKiB: 131072,
	iterations: 3,
	parallelism: 1,
	hashLength: 32,
	saltLength: 16
};

const ARGON2_MINIMUM_ACCEPTABLE_PROFILE: Argon2Profile = {
	name: 'minimum-acceptable',
	memoryKiB: 65536,
	iterations: 3,
	parallelism: 1,
	hashLength: 32,
	saltLength: 16
};

const ARGON2_CONTROLLED_FALLBACK_PROFILE: Argon2Profile = {
	name: 'controlled-fallback',
	memoryKiB: 19456,
	iterations: 2,
	parallelism: 1,
	hashLength: 32,
	saltLength: 16
};

const ARGON2_PROFILES = {
	recommendedStandard: ARGON2_RECOMMENDED_STANDARD_PROFILE,
	minimumAcceptable: ARGON2_MINIMUM_ACCEPTABLE_PROFILE,
	controlledFallback: ARGON2_CONTROLLED_FALLBACK_PROFILE
} as const;

export {
	ARGON2_CONTROLLED_FALLBACK_PROFILE,
	ARGON2_MINIMUM_ACCEPTABLE_PROFILE,
	ARGON2_PROFILES,
	ARGON2_RECOMMENDED_STANDARD_PROFILE,
	PCBK_AES_GCM_TAG_BITS,
	PCBK_BACKUP_ID_BYTES,
	PCBK_BIP39_ENTROPY_BITS,
	PCBK_BIP39_WORD_COUNT,
	PCBK_CLEAR_HEADER_LENGTH_BYTES,
	PCBK_CONTENT_KEY_BYTES,
	PCBK_FLAGS,
	PCBK_FORMAT_VERSION,
	PCBK_HEADER_AUTH_INFO,
	PCBK_HEADER_AUTH_TAG_BYTES,
	PCBK_HEADER_VERSION,
	PCBK_HKDF_ALGORITHM,
	PCBK_KDF_ALGORITHM,
	PCBK_KEY_WRAP_ALGORITHM,
	PCBK_KEY_WRAP_INFO,
	PCBK_MAGIC,
	PCBK_RECORD_CIPHER_ALGORITHM,
	PCBK_RECORD_HEADER_LENGTH_BYTES,
	PCBK_RECORD_NONCE_BYTES,
	PCBK_RECORD_NONCE_PREFIX_BYTES,
	PCBK_RECORD_VERSION,
	PCBK_ROOT_KEY_BYTES,
	PCBK_SALT_BYTES,
	PCBK_WRAP_IV_BYTES
};