export {
	generateExportableEncryptionKeyPair,
	generateExportableSigningKeyPair,
	exportPublicKey,
	exportPrivateKeyPkcs8,
	importPublicKey,
	importPrivateKeyPkcs8,
	importKeyPairFromExported,
	deriveSharedKey,
	generateSymmetricKey,
	exportSymmetricKey,
	importSymmetricKey,
	createIdentityPayload,
	validateIdentityPayload,
	createIdentityCapsule,
	unlockIdentityCapsule,
	encryptMessage,
	decryptMessage,
	encryptBytes,
	encryptBytesWithIv,
	decryptBytes,
	signData,
	verifySignature,
	hashBytes,
	concatArrayBuffers,
	hashPublicKey,
	generateFingerprint,
	arrayBufferToBase64,
	base64ToArrayBuffer,
	type KeyPair,
	type ExportedKeyPair,
	type IdentityKeyMaterial,
	type IdentityPayload,
	type ProtectedIdentityCapsule,
} from './crypto-service';
export { db as keyDatabase, storeKeyPair, getKeyPair, hasKeys, storeIdentityCapsule, getIdentityCapsule, clearIdentityCapsule, storePeerKey, getPeerKey, getAllPeerKeys, deletePeerKey, updatePeerDisplayName, markPeerKeyVerified, clearAllKeys } from './key-manager';
